ALTER TABLE session_snapshots ADD COLUMN IF NOT EXISTS bid_volume_5 DOUBLE PRECISION;
ALTER TABLE session_snapshots ADD COLUMN IF NOT EXISTS ask_volume_5 DOUBLE PRECISION;
ALTER TABLE session_snapshots ADD COLUMN IF NOT EXISTS bid_volume_10 DOUBLE PRECISION;
ALTER TABLE session_snapshots ADD COLUMN IF NOT EXISTS ask_volume_10 DOUBLE PRECISION;
ALTER TABLE session_snapshots ADD COLUMN IF NOT EXISTS imbalance_ratio DOUBLE PRECISION;
ALTER TABLE session_snapshots ADD COLUMN IF NOT EXISTS up_probability DOUBLE PRECISION;
ALTER TABLE session_snapshots ADD COLUMN IF NOT EXISTS down_probability DOUBLE PRECISION;
