use std::collections::HashMap;
use std::fs::{File, OpenOptions};
use std::io::{BufWriter, Write};
use std::sync::Mutex;

use tracing::{info, warn};

use crate::modules::hft::types::{CsvRecord, EventType};

/// Write column descriptions as # comment lines before the header row.
fn write_column_metadata(w: &mut BufWriter<File>) {
    let _ = writeln!(w, "# build_version={} built@{}", env!("GIT_VERSION"), env!("BUILD_TIME"));
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# ============================================================");
    let _ = writeln!(w, "# ZZIGNAL CSV — Odiseo 83 HFT Bot — Column Reference");
    let _ = writeln!(w, "# ============================================================");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# STRATEGY: Odiseo 83");
    let _ = writeln!(w, "#   Entry: trade_up >= 0.83 (UP) or trade_dn >= 0.83 (DOWN)");
    let _ = writeln!(w, "#   TP: 0.97 (+16.9%)  SL-hard: 0.81 (-2.4%)  SL-trend: -0.03  SL-micro: vol drop >30%");
    let _ = writeln!(w, "#   Budget: $20 default  Profit stop: 15%  Max SL/session: 4  Reinvest: ON");
    let _ = writeln!(w, "#   Boundary protect: no entries first 60s + last 45s (flash exit=reason 6)");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# STATUS CODES (od83_up / od83_dn):");
    let _ = writeln!(w, "#   0 = idle/blocked  1 = WATCHING (waiting for entry)  2 = ACTIVE (in position)");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# EXIT REASON CODES (od83_up_r / od83_dn_r):");
    let _ = writeln!(w, "#   0 = no exit (active)  1 = TP  2 = SL-micro  3 = SL-trend");
    let _ = writeln!(w, "#   4 = SL-hard  5 = session settle  6 = flash_protection (NOT counted as SL)");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# PNL FORMULA:");
    let _ = writeln!(w, "#   paper: (exit_price - entry_price) * size   live: from Polymarket fills");
    let _ = writeln!(w, "#   slippage = paper_pnl - live_pnl");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# RISK SCORES:");
    let _ = writeln!(w, "#   dump_score: 0=safe 1=warning(vol dropping) 2=critical(ask wall) 3=dead(bid=0)");
    let _ = writeln!(w, "#   reversal_score: 0=safe 1=alert 2=danger 3=exit_now");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# ANALYSIS GUIDE (for LLMs):");
    let _ = writeln!(w, "#   1. Filter by session: group rows by 15-min windows on `time`");
    let _ = writeln!(w, "#   2. Detect trades: od83_up transitions 1->2 = entry, 2->0 = exit");
    let _ = writeln!(w, "#   3. PnL per trade: last od83_up_pnl before exit (where od83_up_r > 0)");
    let _ = writeln!(w, "#   4. Win rate: PnL > 0 / total trades   Profit factor: sum(pos) / |sum(neg)|");
    let _ = writeln!(w, "#   5. Correlate exits with: dump_score, reversal_score, tick_gap_ms, bid_drain");
    let _ = writeln!(w, "#   6. LIVE vs PAPER: compare od83_up_pnl (paper) with live_up (real)");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "# Session: 15-min Polymarket, independent budgets, reinvest carries PnL forward");
    let _ = writeln!(w, "# Timezone: UTC-5 (Lima/Bogota)");
    let _ = writeln!(w, "# ============================================================");
    let _ = writeln!(w, "#");
    let _ = writeln!(w, "#  COL NAME                 TYPE         DESCRIPTION                                       ");
    let _ = writeln!(w, "# ---- -------------------- ------------ --------------------------------------------------");
    let _ = writeln!(w, "#    1 time                 timestamp    Local timestamp UTC-5                             ");
    let _ = writeln!(w, "#    2 ts_exchange          int64        Binance exchange timestamp                        ");
    let _ = writeln!(w, "#    3 event                string       Event type                                        ");
    let _ = writeln!(w, "#    4 latencia_ms          int          Cross-exchange latency                            ");
    let _ = writeln!(w, "#    5 binance_price        float        BTC mid price                                     ");
    let _ = writeln!(w, "#    6 binance_micro_price  float        Volume-weighted micro price                       ");
    let _ = writeln!(w, "#    7 binance_imbalance    float        Depth imbalance                                   ");
    let _ = writeln!(w, "#    8 binance_vol_100ms    float        BTC volume last 100ms                             ");
    let _ = writeln!(w, "#    9 binance_vol_24h      float        BTC 24h volume                                    ");
    let _ = writeln!(w, "#   10 bid                  float        Polymarket best bid                               ");
    let _ = writeln!(w, "#   11 ask                  float        Polymarket best ask                               ");
    let _ = writeln!(w, "#   12 mid                  float        Polymarket mid price                              ");
    let _ = writeln!(w, "#   13 spread               float        ask - bid                                         ");
    let _ = writeln!(w, "#   14 bid_vol              float        Total bid volume                                  ");
    let _ = writeln!(w, "#   15 ask_vol              float        Total ask volume                                  ");
    let _ = writeln!(w, "#   16 imbalance            float        Order book imbalance                              ");
    let _ = writeln!(w, "#   17 trades_per_second    float        Binance trade rate                                ");
    let _ = writeln!(w, "#   18 btc_vel              float        BTC price velocity                                ");
    let _ = writeln!(w, "#   19 poly_liquidity_delta float        Δ ask volume                                      ");
    let _ = writeln!(w, "#   20 absorption_ratio     float        Absorption ratio                                  ");
    let _ = writeln!(w, "#   21 price_gap_ratio      float        % divergence                                      ");
    let _ = writeln!(w, "#   22 spoof                int          Spoofing flag                                     ");
    let _ = writeln!(w, "#   23 tape                 int          Tape speed flag                                   ");
    let _ = writeln!(w, "#   24 gap                  int          Gap alert flag                                    ");
    let _ = writeln!(w, "#   25 pnr_active           int          PNR window active                                 ");
    let _ = writeln!(w, "#   26 secs_left            int          Seconds until session close                       ");
    let _ = writeln!(w, "#   27 pnr_price            float        poly_mid at PNR                                   ");
    let _ = writeln!(w, "#   28 pnr_return_up        float        Expected UP return                                ");
    let _ = writeln!(w, "#   29 pnr_return_down      float        Expected DOWN return                              ");
    let _ = writeln!(w, "#   30 pnr_volatility_1m    float        Volatility proxy                                  ");
    let _ = writeln!(w, "#   31 pnr_confidence       float        PNR confidence                                    ");
    let _ = writeln!(w, "#   32 pnr_trend            int          PNR trend direction                               ");
    let _ = writeln!(w, "#   33 pnr_spread_pct       float        Spread ratio                                      ");
    let _ = writeln!(w, "#   34 p_bid_lo             float        Pressure bid floor                                ");
    let _ = writeln!(w, "#   35 p_ask_hi             float        Pressure ask ceiling                              ");
    let _ = writeln!(w, "#   36 p_band               float        Pressure band width                               ");
    let _ = writeln!(w, "#   37 p_index              float        Pressure index                                    ");
    let _ = writeln!(w, "#   38 p_skew               float        Pressure volume skew                              ");
    let _ = writeln!(w, "#   39 od83_up              int          Odiseo 83 UP status                               ");
    let _ = writeln!(w, "#   40 od83_up_entry        float        UP entry fill price                               ");
    let _ = writeln!(w, "#   41 od83_up_sz           float        UP contracts bought                               ");
    let _ = writeln!(w, "#   42 od83_up_pnl          float        UP paper PnL                                      ");
    let _ = writeln!(w, "#   43 od83_up_exit         float        UP exit fill price                                ");
    let _ = writeln!(w, "#   44 od83_up_r            int          UP exit reason                                    ");
    let _ = writeln!(w, "#   45 od83_up_bal          float        UP balance                                        ");
    let _ = writeln!(w, "#   46 od83_dn              int          Odiseo 83 DOWN status                             ");
    let _ = writeln!(w, "#   47 od83_dn_entry        float        DOWN entry fill price                             ");
    let _ = writeln!(w, "#   48 od83_dn_sz           float        DOWN contracts sold                               ");
    let _ = writeln!(w, "#   49 od83_dn_pnl          float        DOWN paper PnL                                    ");
    let _ = writeln!(w, "#   50 od83_dn_exit         float        DOWN exit fill price                              ");
    let _ = writeln!(w, "#   51 od83_dn_r            int          DOWN exit reason                                  ");
    let _ = writeln!(w, "#   52 od83_dn_bal          float        DOWN balance                                      ");
    let _ = writeln!(w, "#   53 live_up              float        Real UP PnL                                       ");
    let _ = writeln!(w, "#   54 live_dn              float        Real DOWN PnL                                     ");
    let _ = writeln!(w, "#   55 live_bal             float        Real USDC balance                                 ");
    let _ = writeln!(w, "#   56 od_signal            int          Odiseo entry signal                               ");
    let _ = writeln!(w, "#   57 trade_up             float        Last trade price UP                               ");
    let _ = writeln!(w, "#   58 trade_dn             float        Last trade price DOWN                             ");
    let _ = writeln!(w, "#   59 od83_up_mode         string       UP trade mode                                     ");
    let _ = writeln!(w, "#   60 od83_dn_mode         string       DOWN trade mode                                   ");
    let _ = writeln!(w, "#   61 od83_up_at           timestamp    UP entry timestamp                                ");
    let _ = writeln!(w, "#   62 od83_dn_at           timestamp    DOWN entry timestamp                              ");
    let _ = writeln!(w, "#   63 od83_up_fill_ms      int          UP fill latency                                   ");
    let _ = writeln!(w, "#   64 od83_dn_fill_ms      int          DOWN fill latency                                 ");
    let _ = writeln!(w, "#   65 tick_gap_ms          int          ms since last tick                                ");
    let _ = writeln!(w, "#   66 bid_drain            float        % bid vol lost                                    ");
    let _ = writeln!(w, "#   67 ask_wall             int          Ask wall flag                                     ");
    let _ = writeln!(w, "#   68 dump_score           int          Flash dump risk                                   ");
    let _ = writeln!(w, "#   69 btc_delta            float        BTC change since entry                            ");
    let _ = writeln!(w, "#   70 mid_from_entry       float        Distance from entry                               ");
    let _ = writeln!(w, "#   71 adverse_ticks        int          Ticks moving against                              ");
    let _ = writeln!(w, "#   72 vol_bleed            float        % volume lost                                     ");
    let _ = writeln!(w, "#   73 reversal_score       int          Reversal risk                                     ");

}